# Generated by Django 5.0.3 on 2024-03-29 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_place_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placecomment',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='places.place'),
        ),
    ]
