# Generated by Django 5.0.3 on 2024-03-30 00:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_alter_placecomment_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='placecomment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
